export interface PrivacyBlock {
  subtitle: string;
  text: string;
}

export interface PrivacySection {
  id: string;
  number: string;
  title: string;
  blocks: PrivacyBlock[];
}

export interface PrivacyMeta {
  title: string;
  subtitle: string;
  description: string;
  effectiveDate: string;
  region: string;
}

export interface PrivacyPolicyDocument {
  meta: PrivacyMeta;
  sections: PrivacySection[];
}

export const privacyPolicy: PrivacyPolicyDocument = {
  meta: {
    title: 'Privacy Policy',
    subtitle: 'Your journey, your data.',
    description:
      'Rihla is built by students, for students. We believe travel should be free — including from surveillance. Here\'s exactly what we collect, why, and how we protect it.',
    effectiveDate: 'April 2026',
    region: 'Morocco',
  },
  sections: [
    {
      id: 'information',
      number: '01',
      title: 'Information We Collect',
      blocks: [
        {
          subtitle: 'Account & Profile Data',
          text: 'When you register on Rihla, we collect your email address, username, display name, avatar, and bio. If you sign in via Google or 42 Intra OAuth, we receive basic profile information from those providers — only what\'s necessary to create your account.',
        },
        {
          subtitle: 'Travel & Activity Data',
          text: 'We store the places you save, the cities you explore, your travel plans generated by our AI planner, and the reviews you leave. This data powers your personal journey history and helps us improve recommendations.',
        },
        {
          subtitle: 'Communications',
          text: "Messages exchanged through Rihla's real-time chat feature are stored to deliver them reliably. Friend connections and notification preferences are also retained.",
        },
      ],
    },
    {
      id: 'usage',
      number: '02',
      title: 'How We Use Your Data',
      blocks: [
        {
          subtitle: 'Core Platform Services',
          text: 'Your data powers everything you experience on Rihla: personalized place discovery, AI-generated trip plans, saved itineraries, community reviews, and real-time connections with fellow student travellers.',
        },
        {
          subtitle: 'AI & Recommendations',
          text: 'Our Gemini-powered trip planner uses your preferences and saved places to generate tailored travel suggestions across Morocco. This processing happens server-side; your data is not used to train third-party AI models.',
        },
        {
          subtitle: 'Safety & Security',
          text: 'We analyze usage patterns to detect fraud, abuse, and unauthorized access. CSRF tokens and JWT authentication protect every session.',
        },
      ],
    },
    {
      id: 'sharing',
      number: '03',
      title: 'Data Sharing',
      blocks: [
        {
          subtitle: 'We Do Not Sell Your Data',
          text: 'Rihla does not sell, rent, or trade your personal information to any third party for commercial purposes. Your journey is yours.',
        },
        {
          subtitle: 'Service Providers',
          text: 'We work with Google (Places API, OAuth), Gemini AI, and infrastructure providers to deliver our services. These partners are contractually bound to protect your data and use it only to serve Rihla.',
        },
        {
          subtitle: 'Public Profile Information',
          text: 'Your username, display name, avatar, and public reviews are visible to other Rihla users. Your saved places can be shared publicly or kept private — your choice.',
        },
      ],
    },
    {
      id: 'rights',
      number: '04',
      title: 'Your Rights',
      blocks: [
        {
          subtitle: 'Access & Portability',
          text: 'You can view and download all data associated with your account at any time from your profile settings. We provide this in a standard, machine-readable format.',
        },
        {
          subtitle: 'Correction & Deletion',
          text: 'Edit your profile, change your password, or unlink OAuth providers directly from Settings. To permanently delete your account and all associated data, contact us — we\'ll complete the request within 30 days.',
        },
        {
          subtitle: 'Withdrawal of Consent',
          text: 'You may revoke OAuth provider access at any time through your linked providers settings. Doing so will not delete your account but will remove that login method.',
        },
      ],
    },
    {
      id: 'security',
      number: '05',
      title: 'Security',
      blocks: [
        {
          subtitle: 'Technical Safeguards',
          text: 'Passwords are hashed with Argon2. Sessions use HTTP-only cookies with CSRF protection. All inter-service communication is authenticated via JWT. Secrets are managed through HashiCorp Vault.',
        },
        {
          subtitle: 'Data Minimization',
          text: 'We collect only what is necessary. Sensitive credentials (OAuth tokens, API keys) are never exposed to the frontend and are rotated regularly.',
        },
        {
          subtitle: 'Incident Response',
          text: 'In the event of a data breach, affected users will be notified within 72 hours via the email address on their account.',
        },
      ],
    },
    {
      id: 'cookies',
      number: '06',
      title: 'Cookies',
      blocks: [
        {
          subtitle: 'Essential Cookies',
          text: 'We use HTTP-only cookies to store your authentication token and a readable CSRF token required for account security. These are strictly necessary for the platform to function.',
        },
        {
          subtitle: 'No Tracking Cookies',
          text: 'Rihla does not use advertising cookies, third-party analytics trackers, or fingerprinting technologies. We don\'t serve ads — ever.',
        },
        {
          subtitle: 'Redis Sessions',
          text: 'Session state and API rate-limiting data are stored temporarily in Redis and expire automatically.',
        },
      ],
    },
    {
      id: 'contact',
      number: '07',
      title: 'Contact & Updates',
      blocks: [
        {
          subtitle: 'Questions',
          text: 'If you have questions about this policy or how your data is handled, reach out to our team via the contact information in your account settings or through our GitHub Issues page.',
        },
        {
          subtitle: 'Policy Changes',
          text: 'We will notify users of material changes to this Privacy Policy via email at least 14 days before they take effect. Continued use of Rihla after that date constitutes acceptance.',
        },
        {
          subtitle: 'Effective Date',
          text: 'This Privacy Policy is effective as of April 2026 and applies to all users of the Rihla platform.',
        },
      ],
    },
  ],
};
